### ISSUE TITLE
화이팅! 응원해요-! :D

### ISSUE THREAD

**Issue by blackturtle2** [joeseonmi/woosan_weather#39]
오랜만에 깃헙 투어 하다가 선미님 깃헙에도 놀러왔어요.
발도장을 남기고 싶어서, 첫 이슈로. 🌈 

우산챙기개, 화이팅! 기대되요! 😆 
( 런치스크린 완전 귀엽귀엽. ㅋㅋ )

~이 이슈는 셀프-클로즈하셔도 괜찮아요.ㅋㅋㅋㅋ~

**Comment by joeseonmi** [comment]
지금봤네요ㅋㅋㅋㅋㅋ 곧 출시에여! 🤯 
재성님도 화이팅입니돠ㅋㅋㅋ
